#!/bin/sh

case "${1}" in
  --cluster-name)
    CLUSTER_NAME="${2}"
    shift 2
  ;;
  name-node)
    hdfs namenode -format "${CLUSTER_NAME}"
    hdfs --daemon start namenode
  ;;
  secondary-name-node)
    hdfs namenode -format "${CLUSTER_NAME}"
    hdfs --deamon start secondarynamenode
  ;;
  data-node)
    hdfs namenode -format "${CLUSTER_NAME}"
    hdfs --daemon start datanode
  ;;
  resource-manager)
    yarn --daemon start resourcemanager
  ;;
  node-manager)
    yarn --daemon start nodemanager
  ;;
  proxy-server)
    yarn --daemon start proxyserver
  ;;
  history-server)
    mapred --daemon start historyserver
  ;;
  *)
    echo "Unknown argument: ${1}" >&2
    exit 1
  ;;
esac
