#!/bin/sh

case "${1}" in
  --zookeeper)
    ${KAFKA_HOME}/bin/zookeeper-server-start.sh "${KAFKA_HOME}/config/zookeeper.properties"
  ;;
  --server)
    ${KAFKA_HOME}/bin/kafka-server-start.sh "${KAFKA_HOME}/config/server.properties"
  ;;
  *)
    echo "Unknown argument: ${1}" >&2
    exit 1
  ;;
esac
