name: styx

on:
  push:
    branches: ci

jobs:
  docker-kerberos:
    name: Dist Kerberos to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubToken }}
    - name: Build and Push styx:kerberos
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chenzhe0722/styx:kerberos
        context: docker/styx/kerberos
        file: docker/styx/kerberos/Dockerfile
        platforms: linux/amd64,linux/arm64

  docker-kafka:
    name: Dist Kafka to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubToken }}
    - name: Build and Push styx:kafka
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chenzhe0722/styx:kafka
        context: docker/styx/kafka
        file: docker/styx/kafka/Dockerfile
        platforms: linux/amd64,linux/arm64

  docker-hadoop:
    name: Dist Hadoop to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubToken }}
    - name: Build and Push styx:hadoop
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chenzhe0722/styx:hadoop
        context: docker/styx/hadoop
        file: docker/styx/hadoop/Dockerfile
        platforms: linux/amd64,linux/arm64

  docker-hive:
    name: Dist Hive to DockerHub
    runs-on: ubuntu-latest
    needs: [docker-hadoop]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubToken }}
    - name: Build and Push styx:hive
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chenzhe0722/styx:hive
        context: docker/styx/hive
        file: docker/styx/hive/Dockerfile
        platforms: linux/amd64,linux/arm64

  docker-spark:
    name: Dist Spark to DockerHub
    runs-on: ubuntu-latest
    needs: [docker-hive]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubToken }}
    - name: Build and Push styx:spark
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chenzhe0722/styx:spark
        context: docker/styx/spark
        file: docker/styx/spark/Dockerfile
        platforms: linux/amd64,linux/arm64
